const display=document.getElementById('display'),expression=document.getElementById('expression'),keypad=document.getElementById('keypad'),themeToggle=document.getElementById('themeToggle');
const historyList=document.getElementById('historyList'),historyCount=document.getElementById('historyCount');
let current='0',previous=null,operator=null,resetNext=false,memory=0,exprText='',history=JSON.parse(localStorage.getItem('anindyaCalcHistory')||'[]');
const symbols={"*":"×","/":"÷","-":"−","+":"+"};
const $=id=>document.getElementById(id); function trim(n){if(typeof n==='string')return n; if(!Number.isFinite(n))return 'Error'; return Number.isInteger(n)?String(n):String(Number(n.toPrecision(12)))}
function render(){display.textContent=current;expression.textContent=exprText||'Ready'}
function inputDigit(d){if(current==='Error'||resetNext){current=d;resetNext=false}else current=current==='0'?d:current+d;render()}
function inputDecimal(){if(current==='Error'||resetNext){current='0.';resetNext=false}else if(!current.includes('.'))current+='.';render()}
function clearAll(){current='0';previous=null;operator=null;resetNext=false;exprText='';render()}
function backspace(){if(resetNext||current==='Error')return;if(current.length<=1||current==='-0')current='0';else current=current.slice(0,-1);render()}
function chooseOperator(op){if(current==='Error')return;const value=Number(current);if(previous!==null&&operator&&!resetNext){calculate(false);previous=Number(current)}else previous=value;operator=op;resetNext=true;exprText=`${trim(previous)} ${symbols[op]}`;render()}
function calculate(show=true){if(previous===null||!operator)return;const a=previous,b=Number(current);let result;switch(operator){case '+':result=a+b;break;case '-':result=a-b;break;case '*':result=a*b;break;case '/':result=b===0?NaN:a/b;break}const shown=trim(result);if(shown==='Error'){current='Error';exprText='Cannot divide by zero';previous=null;operator=null;resetNext=true;render();return}current=shown;if(show){exprText=`${trim(a)} ${symbols[operator]} ${trim(b)} =`;addHistory(exprText,current)}previous=null;operator=null;resetNext=true;render()}
function percent(){if(current==='Error')return;current=trim(Number(current)/100);exprText=`${current} =`;render()}
function sign(){if(current!=='0'&&current!=='Error')current=current.startsWith('-')?current.slice(1):'-'+current;render()}
function memoryClear(){memory=0;expression.textContent='Memory cleared'}function memoryRecall(){current=trim(memory);resetNext=false;render()}function memoryAdd(){memory+=Number(current)||0;expression.textContent=`M = ${trim(memory)}`}function memorySubtract(){memory-=Number(current)||0;expression.textContent=`M = ${trim(memory)}`}
function scientific(fn){if(current==='Error')return;const x=Number(current);let r,label;const rad=x*Math.PI/180;switch(fn){case'sin':r=Math.sin(rad);label=`sin(${x}°)`;break;case'cos':r=Math.cos(rad);label=`cos(${x}°)`;break;case'tan':r=Math.tan(rad);label=`tan(${x}°)`;break;case'sqrt':r=Math.sqrt(x);label=`√(${x})`;break;case'square':r=x*x;label=`${x}²`;break;case'cube':r=x*x*x;label=`${x}³`;break;case'ln':r=Math.log(x);label=`ln(${x})`;break;case'log':r=Math.log10(x);label=`log(${x})`;break;case'pi':r=Math.PI;label='π';break;case'e':r=Math.E;label='e';break;case'inverse':r=x===0?NaN:1/x;label=`1/${x}`;break;case'factorial':r=factorial(x);label=`${x}!`;break}current=trim(r);exprText=`${label} =`;if(current!=='Error')addHistory(exprText,current);resetNext=true;render()}
function factorial(n){if(n<0||n>170||n%1!==0)return NaN;let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function addHistory(exp,res){history.unshift({exp,res,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});history=history.slice(0,30);localStorage.setItem('anindyaCalcHistory',JSON.stringify(history));renderHistory()}
function renderHistory(){historyCount.textContent=history.length;if(!history.length){historyList.innerHTML='<div class="empty-history">Your calculations will appear here.</div>';return}historyList.innerHTML=history.map((h,i)=>`<div class="history-item" data-index="${i}"><div class="history-expression">${escapeHtml(h.exp)}</div><div class="history-result">${escapeHtml(h.res)}</div><div class="history-time">${h.time}</div></div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
keypad.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const v=b.dataset.value,a=b.dataset.action;if(v!==undefined){if(/^\d$/.test(v))inputDigit(v);else if(v==='.')inputDecimal();else chooseOperator(v);return}if(a==='clear')clearAll();if(a==='sign')sign();if(a==='percent')percent();if(a==='equals')calculate();if(a==='backspace')backspace()});
document.querySelector('.memory-row').addEventListener('click',e=>{const a=e.target.closest('button')?.dataset.action;if(a==='memory-clear')memoryClear();if(a==='memory-recall')memoryRecall();if(a==='memory-add')memoryAdd();if(a==='memory-subtract')memorySubtract();if(a==='backspace')backspace()});
document.querySelector('.scientific-pad').addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.fn)scientific(b.dataset.fn)});
document.addEventListener('keydown',e=>{if(/^\d$/.test(e.key))inputDigit(e.key);else if(e.key==='.')inputDecimal();else if(['+','-','*','/'].includes(e.key))chooseOperator(e.key);else if(e.key==='Enter'||e.key==='=')calculate();else if(e.key==='Escape')clearAll();else if(e.key==='Backspace')backspace();else if(e.key==='%')percent()});
$('scientificBtn').onclick=()=>{$('scientificPad').classList.remove('hidden');$('scientificBtn').classList.add('active');$('standardBtn').classList.remove('active')};$('standardBtn').onclick=()=>{$('scientificPad').classList.add('hidden');$('standardBtn').classList.add('active');$('scientificBtn').classList.remove('active')};
$('clearHistory').onclick=()=>{history=[];localStorage.removeItem('anindyaCalcHistory');renderHistory()};historyList.addEventListener('click',e=>{const item=e.target.closest('.history-item');if(!item)return;current=history[Number(item.dataset.index)].res;resetNext=false;exprText=history[Number(item.dataset.index)].exp;render()});
themeToggle.addEventListener('click',()=>{document.body.classList.toggle('light');themeToggle.textContent=document.body.classList.contains('light')?'☀':'☾';localStorage.setItem('anindyaCalcTheme',document.body.classList.contains('light')?'light':'dark')});if(localStorage.getItem('anindyaCalcTheme')==='light'){document.body.classList.add('light');themeToggle.textContent='☀'}render();renderHistory();
